### ISSUE TITLE
Class passed to lwce-link is getting attached to both lwce-link and <a> tag in it

### ISSUE THREAD

**Issue by vsanse** [LWC-Essentials/router#3]
Class passed to lwce-link is getting attached to both lwce-link and <a> tag in it. This is causing styling issues. I would suggest keeping a public property like `classname` on lwce-link which will be applied to a tag as class.

**Comment by blittle** [comment]
@vsanse I think this resolves the issue: https://github.com/LWC-Essentials/router/pull/4/files. Originally I wanted the API of `lwce-link` to look identical to a normal anchor tag. That goal may not be feasible. Though another option might be to constantly watch the `class` attribute on `lwce-link` and store it as another variable to pass to the anchor tag. Then after storing it, remove it from `lwce-link`. This seems like it has the potential to have weird rendering issues.

**Comment by vsanse** [comment]
@blittle, yes this will resolve the issue of style leaking to both anchor tag and lwce-link tag

**Comment by blittle** [comment]
Resolved with v1.0.0
